apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cp2-ingress
  namespace: cp2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /()(.*)
        pathType: Prefix
        backend:
          service:
            name: web-cp2-svc
            port:
              number: 80
      - path: /aks(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: web-aks-cp2-svc
            port:
              number: 80
