apiVersion: v1
kind: Service
metadata:
  name: web-aks-cp2-svc
  namespace: cp2
spec:
  type: LoadBalancer
  selector:
    app: web-aks-cp2
  ports:
    - name: http
      port: 80
      targetPort: 80
